[[rule]]
name="critical-save-power"
if.all = [
  "?discharging",
  { is-less-than = 0.3, value = "%power-supply-charge" }
]
priority = 90

cpu.governor = "powersave"
cpu.energy-performance-preference = "power"
cpu.frequency-mhz-maximum = 200
cpu.turbo = false
power.platform-profile = "low-power"

#discharging
[[rule]]
name="low-then-minimise-stuff"
if.all = [
  "?discharging",
  { is-less-than = 0.5, value = "%power-supply-charge" }
]
priority = 11

cpu.governor = "powersave"
cpu.frequency-mhz-maximum = 2000
cpu.turbo = false
cpu.energy-performance-preference = "power"

[[rule]]
name="save-power-generally"
if = "?discharging"
priority = 10

cpu.governor = "powersave"
cpu.energy-performance-preference = "power"
cpu.turbo = false


[[rule]]
name = "maximise-perf-high-power"
if.all = [
  { is-more-than = 0.8, value = { cpu-usage-since = "10sec" } },
  { is-less-than = 15.0, value = "$cpu-idle-seconds" },
  { is-less-than = 80.0, value = "$cpu-temperature" },
]
priority = 80

cpu.governor = "performance"
cpu.energy-performance-preference = "performance"
power.platform-profile = "performance"
cpu.turbo = true
