name: build-systems
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  find-systems:
    name: find-systems
    runs-on: ubuntu-latest
    outputs:
      nixos: ${{ steps.finder.outputs.nixos }}
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - id: finder
        run: |
          nixos=$(nix eval --accept-flake-config --quiet .#.lib.hostsBySystem --apply 'f: f "x86_64-linux"' --json)

          echo "nixos=$nixos"

          echo "nixos=$nixos" >> $GITHUB_OUTPUT

  x86_64-linux:
    name: ${{ matrix.host }} x86_64-linux
    needs: [find-systems]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJSON(needs.find-systems.outputs.nixos) }}
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v16
        with:
          name: squawkykaka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --accept-flake-config --no-link --print-out-paths .#.nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
